###
POST https://localhost:5001/api/pesssoa/create
Content-Type: application/json

{
    "Nome" : "Laury",
    "Cpf" : "6466262",
    "Email" : "lau@email.com",
    "Telefone" : "4665-67868"
}

###
GET https://localhost:5001/api/pessoa/list
